###测试净距分析接口
GET http://localhost:9081/pipeLineAnalysis/distance
?PIBATCH0=1&TYPE0=WS_NETWORK&SMID0=407
&PIBATCH1=1&TYPE1=WS_NETWORK&SMID1=507

###测试碰撞分析接口
GET http://localhost:9081/pipeLineAnalysis/collision
?PIBATCH0=2&TYPE0=WS_NETWORK
&PIBATCH1=3&TYPE1=WS_NETWORK
&MINDISTANCE=0.001

###测试断面分析接口
Get http://localhost:9081/pipeLineAnalysis/horizontalProfile
?POINT0[0]=-2399984.52723825&POINT0[1]=5367322.9568854915&POINT0[2]=2472421.564441106
&POINT1[0]=-2399958.2658195393&POINT1[1]=5367313.75563679&POINT1[2]=2472470.9196066963
&POINT2[0]=0.0&POINT2[1]=0.0&POINT2[2]=0.0

###测试连接管点信息,输入管点PLPT，爆管分析
Get http://localhost:9081/pipeLineAnalysis/searchNodesByPLPT
?PIPENODE=YS03320358_QXXZ1

###测试连通管线信息,输入管线PLID
Get http://localhost:9081/pipeLineAnalysis/searchNodesByPLID
?PIPELINE=YS02621647_TXXZ1YS02621989_TXXZ1

###输入两根管线的id值，返回最短路径
Get http://localhost:9081/pipeLineAnalysis/connected
?PIPELINE0=YS02621647_TXXZ1YS02621989_TXXZ1&PIPELINE1=YS02621894_TXXZ1YS02621646_TXXZ1

###输入直线两个端点，将直线右侧管线投影到直线所在平面上，
Get http://localhost:9081/pipeLineAnalysis/verticalProfile
?POINT0[0]=-2401100.218089661&POINT0[1]=5365982.181927463&POINT0[2]=2472421.564441106
&POINT1[0]=-2401090.2325399467&POINT1[1]=5366010.970612872&POINT1[2]=2473584.7178883716

###内部测试，爆管分析
Get http://localhost:9081/pipeLineAnalysis/searchNodesByPLPT
?PIPENODE=PLPT_5

###内部测试
Get http://localhost:9081/pipeLineAnalysis/getConnectionGraph

###
GET http://localhost:9081/pipeLineAnalysis/startServer


###
http://127.0.0.1:9081/pipeLineAnalysis/searchNodesByPLPT?PIPENODE=40YS10538

###
POST http://localhost:9081/pipeLineAnalysis/searchNodesByPLPTPostUp HTTP/1.1
header name: header value

content
{
    "PIPENODE": [
        "40YS18355",
        "40YS19844"
    ]
}